# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PL2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PL2

  pod "GraphicsRenderer", "1.3.0"
  pod 'SVProgressHUD'
  pod 'Firebase/Core', '10.5.0'
  pod 'FBSDKCoreKit', '~> 8.0.0'
  pod 'FBSDKShareKit', '~> 8.0.0'
  #  pod 'FacebookShare'
  #  pod 'FacebookCore'
  pod 'CloudCore', '~> 1.0'
  pod 'FirebaseAnalytics', '10.5.0'
  pod 'Firebase/Crashlytics'
  #pod 'Firebase/AdMob'
  #pod 'Firebase/Core'
  pod 'FirebasePerformance'

  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'SwiftyStoreKit'
  pod 'Firebase/RemoteConfig'
  pod 'GoogleMobileAdsMediationAdColony'
  pod 'GoogleMobileAdsMediationFacebook'
  pod 'GoogleMobileAdsMediationAppLovin'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end
end
